kind: pipeline
name: default

steps:
- name: OSQ
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - qio platform install file://.
  - qio run -d examples/blink
  - qio run -d examples/pumbaa-blink
  - qio run -d examples/simba-blink
