kind: pipeline
name: OSQ

steps:
- name: example
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio platform install https://github.com/OS-Q/P51/archive/pio.zip
  - pio run -d examples/arduino-blink
  - pio run -d examples/arduino-wifiscan
  - pio run -d examples/pumbaa-blink
  - pio run -d examples/simba-blink
