language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wifiscan
  - PLATFORMIO_PROJECT_DIR=examples/pumbaa-blink
  - PLATFORMIO_PROJECT_DIR=examples/simba-blink

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio platform install https://github.com/OS-Q/P51/archive/pio.zip

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR
