language: python
python:
  - "3.7"
os:
  - linux

git:
  depth: false

env:
  - PLATFORMIO_PROJECT_DIR=examples/blink
  - PLATFORMIO_PROJECT_DIR=examples/wifiscan
  - PLATFORMIO_PROJECT_DIR=examples/espidf-exceptions
  - PLATFORMIO_PROJECT_DIR=examples/espidf-peripherals-uart
  - PLATFORMIO_PROJECT_DIR=examples/pumbaa-blink
  - PLATFORMIO_PROJECT_DIR=examples/simba-blink

install:
  - git submodule update --init --recursive
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - pio platform install file://.

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
        - https://webhooks.gitter.im
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
