build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-briki-internal-libs"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-wifiscan"
    - PLATFORMIO_PROJECT_DIR: "examples/espidf-arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/espidf-arduino-wifiscan"
    - PLATFORMIO_PROJECT_DIR: "examples/espidf-exceptions"
    - PLATFORMIO_PROJECT_DIR: "examples/espidf-peripherals-uart"
    - PLATFORMIO_PROJECT_DIR: "examples/espidf-ulp-adc"
    - PLATFORMIO_PROJECT_DIR: "examples/espidf-ulp-pulse"
    - PLATFORMIO_PROJECT_DIR: "examples/pumbaa-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/simba-blink"

platform:
  - x64

install:
- cmd: git submodule update --init --recursive
- cmd: SET PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
- cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
- cmd: qio platform install file://.

test_script:
- cmd: qio run -d %PLATFORMIO_PROJECT_DIR%
