version: 2
jobs:
  latest:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "git"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/arduino-blink
            pio run -d examples/pumbaa-blink
            pio run -d examples/simba-blink

workflows:
    version: 2
    run_ci:
        jobs:
            - latest
