version: 2
jobs:
  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/PIO/archive/develop.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/pumbaa-blink
            pio run -d examples/simba-blink
            pio run -d examples/espidf-ulp-adc
  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/PIO/archive/develop.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/pumbaa-blink
            pio run -d examples/simba-blink
            pio run -d examples/espidf-ulp-adc

workflows:
    version: 2
    run_ci:
        jobs:
          - QIO
          - PIO

