name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        examples:
          - "blink"
          - "wifiscan"
          - "simba-blink"
        package:
          - "release"
          - "latest"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install release
        if: matrix.package == 'release'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install https://github.com/OS-Q/P52/releases/latest/download/P52.zip

      - name: Install latest
        if: matrix.package == 'latest'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Folder win
        if: success() && matrix.os == 'windows-latest'
        run: |
          md build

      - name: Folder
        if: success() && matrix.os != 'windows-latest'
        run: |
          mkdir build

      - name: Build
        id: build
        if: success() && github.repository == 'OS-Q/P52'
        run: |
          pio run -d examples/${{ matrix.examples }} > build/log.txt
          echo "::set-output name=status::success"

      - name: Upload
        if: steps.build.outputs.status == 'success' && env.UPLOAD_BUILD == 'true' && matrix.package == 'latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.examples }}
          path: examples/${{ matrix.examples }}/build

      - name: notification
        uses: stopstopstop/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}/${{ matrix.package }}/${{ matrix.examples }}
          message: ${{steps.build.outputs.status}}

  platformio:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7,3.9]
        example:
          - "examples/arduino-blink"
          - "examples/arduino-briki-internal-libs"
          - "examples/arduino-wifiscan"
          - "examples/espidf-arduino-blink"
          - "examples/espidf-arduino-wifiscan"
          - "examples/espidf-aws-iot"
          - "examples/espidf-ble-eddystone"
          - "examples/espidf-coap-server"
          - "examples/espidf-exceptions"
          - "examples/espidf-hello-world"
          - "examples/espidf-http-request"
          - "examples/espidf-peripherals-uart"
          - "examples/espidf-peripherals-usb"
          - "examples/espidf-storage-sdcard"
          - "examples/espidf-storage-spiffs"
          - "examples/espidf-ulp-adc"
          - "examples/espidf-ulp-pulse"
          - "examples/pumbaa-blink"
          - "examples/simba-blink"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: platformio/platform-espressif32
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: espressif32

      - name: Install dependencies
        if: github.repository == 'OS-Q/P52'
        working-directory: espressif32
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip

      - name: Build examples
        working-directory: espressif32
        run: |
          pio run -d ${{ matrix.example }}
