name: nightly

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    if: github.repository == 'OS-Q/P52'
    strategy:
      fail-fast: false
      matrix:
        examples:
          - "blink"
          - "wifiscan"
          - "simba-blink"
          - "pumbaa-blink"
        package:
          - "release"
          - "latest"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7,3.9]


    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install release
        if: matrix.package == 'release'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install https://github.com/OS-Q/P52/releases/latest/download/P52.zip

      - name: Install latest
        if: matrix.package == 'latest'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        id: build
        if: success() && github.repository == 'OS-Q/P52'
        run: |
          pio run -d examples/${{ matrix.examples }}
          echo "::set-output name=status::success"
