name: nightly

on:
  schedule:
    - cron: "0 1 * * *"
# on:
#   push:
#     branches:
#       - master
#       - main

env:
  MONT: "M03"
  PLAT: "P51"
  TEMP: "F51"

jobs:
  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "arduino-wifiscan"
          - "simba-blink"
          - "pumbaa-blink"
          - "arduino-briki-internal-libs"
          - "espidf-aws-iot"
          - "espidf-ble-eddystone"
          - "espidf-coap-server"
          - "espidf-exceptions"
          - "espidf-hello-world"
          - "espidf-http-request"
          - "espidf-peripherals-uart"
          - "espidf-peripherals-usb"
          - "espidf-storage-sdcard"
          - "espidf-storage-spiffs"
          - "espidf-ulp-adc"
          - "espidf-ulp-pulse"
        package: ["master","slave"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install master
        if: matrix.package == 'master'
        run: |
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install file://.

      - name: Install slave
        if: matrix.package == 'slave'
        run: |
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install https://github.com/OS-Q/${{ env.PLAT }}/archive/qio.zip

      - name: Build
        if: success()
        working-directory: examples
        run: |
          qio run -d ${{ matrix.example }}

      # - name: Upload
      #   if: env.UPLOAD_BUILD
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build_${{ matrix.example }}_${{ matrix.package }}
      #     path: examples/${{ matrix.example }}/.pio/build/

  QIO_tail:
    needs:
      - QIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "QIO build failure"

  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "arduino-wifiscan"
          - "simba-blink"
          - "pumbaa-blink"
          - "arduino-briki-internal-libs"
          - "espidf-aws-iot"
          - "espidf-ble-eddystone"
          - "espidf-coap-server"
          - "espidf-exceptions"
          - "espidf-hello-world"
          - "espidf-http-request"
          - "espidf-peripherals-uart"
          - "espidf-peripherals-usb"
          - "espidf-storage-sdcard"
          - "espidf-storage-spiffs"
          - "espidf-ulp-adc"
          - "espidf-ulp-pulse"
        package: ["master","slave"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install master
        if: matrix.package == 'master'
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Install slave
        if: matrix.package == 'slave'
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/${{ env.PLAT }}/archive/pio.zip

      - name: Build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

  PIO_tail:
    needs:
      - PIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "PIO build failure"
