name: PIO

on:
  push:
    branches:
      - pio
    paths:
      - 'boards/**'
      - 'builder/**'
      - 'monitor/**'
      - 'examples/**'
      - 'platform.json'
      - 'platform.py'

jobs:
  CodeCheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: cppcheck
      uses: Qful/check-action@master
      with:
        github_token: ${{ secrets.OSQ_REPO_TOKEN }}
        enable: all
        inconclusive: disable
        inline_suppression: disable
        force_language: c
        force: enable
        max_ctu_depth: 2
        std: c11
        output_file: ./codecheck.txt
        other_options: --bug-hunting --verbose --std=c11

    - name: report
      uses: Qful/check-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: code_check_report
        path: codecheck.txt

  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "arduino-wifiscan"
          - "simba-blink"
          - "pumbaa-blink"
          - "arduino-briki-internal-libs"
          - "espidf-aws-iot"
          - "espidf-ble-eddystone"
          - "espidf-coap-server"
          - "espidf-exceptions"
          - "espidf-hello-world"
          - "espidf-http-request"
          - "espidf-peripherals-uart"
          - "espidf-peripherals-usb"
          - "espidf-storage-sdcard"
          - "espidf-storage-spiffs"
          - "espidf-ulp-adc"
          - "espidf-ulp-pulse"

        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/P51/archive/pio.zip

      - name: Build examples
        id: build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

  pio_tail:
    needs:
      - PIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "PIO failure"
